import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "../Components/Header/Header";
import { Footer } from "../Components/Footer/Footer";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: "#000000" }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
